### ISSUE TITLE
add needrestart fact

### ISSUE THREAD

**Issue by anarcat** [hetznerZA/hetzner-needrestart#23]
it would be nice if facter would tell us if a reboot or restarts are necessary on nodes. maybe two facts:

 * `needrestart_reboot_required`: similar to `apt_reboot_required` except relying on needrestart (which does a better job), by checking if `NEEDRESTART-KSTA` is greater than one. the  `NEEDRESTART-KCUR` and `NEEDRESTART-KEXP` fields could also be provided as sub-fields
 * `needrestart_updates_required`: similar to `apt_has_updates` in spirit, but not in functionality. whether `NEEDRESTART-SVC` is set at all

This would be based on the output of `needrestart -b`. see also https://github.com/liske/needrestart/blob/master/README.batch.md

Makes sense?

**Comment by edward-harley** [comment]
I have tested adding this fact. It does however it increases a puppet run by a few seconds. Across a large fleet it adds up to a substantial amount of time.
As such, at this stage adding this fact does not alight with our objectives, but you are welcome to fork and add the fact.

**Comment by anarcat** [comment]
oh yeah that sounds awful, let's not do that then! :)

it might be best for needrestart to add its output to a textfile collector then, that could be done on a cron job for example...

thanks!
